# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de0e6c526739adcc15665c4ae07ea59a503cda090cd7c2293fa7afa71f9b15c70bbca90a4c73237da14050077459027461ef10f7a683d30b364500a607a7eb76

test:
  secret_key_base: f2c0003abebdcce8dbeff041e39fa77a99e7af8c444adefa411d4032196616f614bc2192aff786865e0c35433c9878f22d96b515ff6bfd8c614faa276d9f7c2e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
